[package]
name = "geodata_reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.18.0"
ehttp = "0.2.0"
prost = "0.9"

[build-dependencies]
prost-build = "0.9"
